a=input("name")
b=input("age")
c=input("college name")
printf("my name is:","my age is", "my college name is")
math=d=("enter the marks")
physics=e=("enter the marks ")
chemistry=f=("enter the marks")
biology=g=("enter the marks")
english=h=("enter the marks")
math=float(math)
physics=float(physics)
chemistry=float(chemistry)
biology=float(biology)
english=float(english)
sum=d+e+f+g+h
print("sum of your marks is:%2f",sum)