a=float(input("enter the marks of first subject "))
b=float(input("enter the marks of second subject"))
c=float(input("enter the marks of third subject"))
d=float(input("enter the marks of fourth subject"))
e=float(input("enter the marks of fifth subject"))
list=[]
list.append(a)
list.append(b)
list.append(c)
list.append(d)
list.append(e)
print(list)
sum=(a+b+c+d+e)
print ("sum= %d",sum)